chore(docs): Upgrade typedoc to version 0.13.0 (#6717)
Building with the current 0.5.10 now fails because it depends on typescript
before 2.4. This causes the following errors:
```
NativeScript@ typedoc /root/NativeScript
> typedoc --tsconfig tsconfig.typedoc.json --out bin/dist/apiref --includeDeclarations --name NativeScript --theme ./node_modules/nativescript-typedoc-theme --excludeExternals --externalPattern "**/+(tns-core-modules|module).d.ts"

Loaded plugin typedoc-plugin-external-module-name

Using TypeScript 2.2.2 from /root/NativeScript/node_modules/typedoc/node_modules/typescript/lib
Error: /root/NativeScript/tns-core-modules/module.d.ts(67)
In ambient enum declarations member initializer must be constant expression.
Error: /root/NativeScript/tns-core-modules/module.d.ts(68)
In ambient enum declarations member initializer must be constant expression.
Error: /root/NativeScript/tns-core-modules/module.d.ts(69)
In ambient enum declarations member initializer must be constant expression.
```

This fix is required to support typeodoc@0.8.0 and above:
https://github.com/NativeScript/nativescript-typedoc-theme/commit/01f94b4ae2ec1b617eec72b2c325f68c390ad091